
import React, { useState, useCallback } from 'react';
import { StoreProvider, useStore } from './store/useStore';
import Sidebar from './components/Sidebar';
import Editor from './components/Editor';
import Toast from './components/Toast';
import SaveConfirmDialog from './components/SaveConfirmDialog';
import SearchResultsPanel from './components/SearchResultsPanel';
import { ONENOTE_PURPLE } from './constants';

const MainLayout: React.FC = () => {
  const { state, setSaved, showToast, addPage } = useStore();
  const [showSaveDialog, setShowSaveDialog] = useState(false);
  const [pendingAction, setPendingAction] = useState<() => void>(() => () => {});

  const activeNotebook = state.notebooks.find(n => n.id === state.activeNotebookId);
  const activeSection = activeNotebook?.sections.find(s => s.id === state.activeSectionId);
  const activePage = activeSection?.pages.find(p => p.id === state.activePageId) || null;

  const getPageDataForExport = useCallback(() => {
    if (!activePage) return null;
    return {
      title: activePage.title,
      content: activePage.content,
      copyAreas: activePage.copyAreas,
      lastModified: activePage.lastModified
    };
  }, [activePage]);

  const triggerFileDownload = useCallback((data: any) => {
    if (!data) return;
    const fileName = data.title || '無題';
    
    const htmlOutput = `
      <!DOCTYPE html>
      <html lang="ja">
      <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>${data.title || '無題のページ'}</title>
        <script src="https://cdn.tailwindcss.com"></script>
        <style>
          body {
            font-family: 'Segoe UI', -apple-system, BlinkMacSystemFont, "Helvetica Neue", "游ゴシック体", YuGothic, "游ゴシック", "Yu Gothic", sans-serif;
            background-color: #f3f2f1;
            color: #323130;
            margin: 0;
            padding: 0;
          }
          .content-area img { max-width: 100%; height: auto; }
          .rich-text { line-height: 1.6; }
        </style>
      </head>
      <body class="min-h-screen">
        <header class="h-12 flex items-center px-8 text-white shadow-md sticky top-0 z-50" style="background-color: ${ONENOTE_PURPLE};">
          <div class="font-bold flex items-center">
            <span class="mr-2 text-xl italic">N</span>
            OneNote Clone Export
          </div>
        </header>

        <main class="max-w-5xl mx-auto bg-white min-h-screen shadow-lg my-0 md:my-8 p-10 md:p-16">
          <div class="mb-10">
            <h1 class="text-4xl font-light border-b border-[#edebe9] pb-4 text-[#323130]">${data.title || '無題のページ'}</h1>
            <div class="text-xs text-[#605e5c] mt-3 font-normal">
              最終更新: ${new Date(data.lastModified).toLocaleString('ja-JP')}
            </div>
          </div>

          <div class="space-y-4 mb-12">
            ${data.copyAreas.map((area: string) => area ? `
              <div class="border-l-4 border-yellow-400 bg-[#fffbeb] p-6 rounded-r-md shadow-sm">
                <div class="text-sm leading-relaxed text-[#323130] rich-text">${area}</div>
              </div>
            ` : '').join('')}
          </div>

          <div class="content-area text-base text-[#323130] rich-text">
            ${data.content}
          </div>
        </main>
        
        <footer class="text-center py-8 text-xs text-gray-400">
          Generated by OneNote Clone
        </footer>
      </body>
      </html>
    `;
    
    const blob = new Blob([htmlOutput], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${fileName}.html`;
    link.click();
    URL.revokeObjectURL(url);
  }, []);

  const handleSave = useCallback(() => {
    const data = getPageDataForExport();
    if (data) {
      triggerFileDownload(data);
      setSaved();
      showToast('HTML形式で保存しました');
    }
    setShowSaveDialog(false);
    pendingAction();
  }, [getPageDataForExport, triggerFileDownload, setSaved, showToast, pendingAction]);

  const handleDontSave = () => {
    setSaved();
    setShowSaveDialog(false);
    pendingAction();
  };

  const handleNewFile = () => {
    const action = () => {
      if (state.activeSectionId) {
        addPage(state.activeSectionId);
      }
    };

    if (state.isDirty) {
      setPendingAction(() => action);
      setShowSaveDialog(true);
    } else {
      action();
    }
  };

  const handleOpenFile = () => {
    const action = () => {
      showToast('HTMLファイルを読み込む機能を実装可能（デモ）');
    };

    if (state.isDirty) {
      setPendingAction(() => action);
      setShowSaveDialog(true);
    } else {
      action();
    }
  };

  return (
    <div className="flex flex-col h-screen w-screen bg-white">
      <header className="h-12 flex items-center px-4 shadow-sm z-30 shrink-0 text-white" style={{ backgroundColor: ONENOTE_PURPLE }}>
        <div className="flex items-center space-x-6">
          <div className="font-bold flex items-center">
            <span className="mr-2">N</span>
            OneNote Clone
          </div>
          <nav className="hidden md:flex space-x-4 text-sm font-medium">
            <button 
              onClick={handleNewFile}
              className="hover:bg-white/10 px-2 py-1 rounded transition-colors"
            >
              新規作成
            </button>
            <button 
              onClick={handleOpenFile}
              className="hover:bg-white/10 px-2 py-1 rounded transition-colors"
            >
              開く
            </button>
            <button 
              onClick={handleSave}
              className="hover:bg-white/10 px-2 py-1 rounded transition-colors"
            >
              エクスポート
            </button>
          </nav>
        </div>
        <div className="ml-auto flex items-center space-x-4">
          <div className="text-sm font-medium hidden sm:block">User Account</div>
          <div className="w-8 h-8 rounded-full bg-purple-400 flex items-center justify-center text-xs border border-purple-300">U</div>
        </div>
      </header>

      <div className="flex flex-1 overflow-hidden">
        <Sidebar />
        {/* activePageId を key に設定することで、ページ切り替え時にコンポーネントを確実に初期化 */}
        <Editor key={activePage?.id || 'none'} page={activePage} />
        <SearchResultsPanel />
      </div>

      <Toast />

      {showSaveDialog && (
        <SaveConfirmDialog
          fileName={activePage?.title ? `${activePage.title}.html` : '無題.html'}
          onSave={handleSave}
          onDontSave={handleDontSave}
          onCancel={() => setShowSaveDialog(false)}
        />
      )}
    </div>
  );
};

const App: React.FC = () => {
  return (
    <StoreProvider>
      <MainLayout />
    </StoreProvider>
  );
};

export default App;
